### PR TITLE
Prettier code for easy to read (index.html)

### PR DESCRIPTION
**Pull request by PunGrumpy**
I'd like to submit a Pull Request for cleaner, more easily readable code. **ONLY index.html**

### CODE REVIEW

**Comment by heapbytes** [comment]
can i get your discord please. haha

**Comment by PunGrumpy** [comment]
sure, my discord: **Grumpy#9760**

**Comment by heapbytes** [comment]
Seems like I can’t dm you, 
lenon#6176

Here dm me i have to talk to you before the merge

**Comment by heapbytes** [comment]
Heyy,  i have to change the whole ui of the web, there's no point of accepting the pull request.

**Pull request closed without merging**
